# Generated by Django 3.1.3 on 2020-11-23 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testapp', '0002_auto_20201123_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='name_id',
        ),
        migrations.AddField(
            model_name='detail',
            name='name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='name', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detail',
            name='usernamedata',
            field=models.ManyToManyField(related_name='detail', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='userdata',
        ),
    ]
