# Generated by Django 3.1.3 on 2020-11-23 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_auto_20201123_1414'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detail',
            old_name='amount',
            new_name='price',
        ),
    ]
